"""Non-blocking WebSocket client + server for CircuitPython, MicroPython, and CPython.

Built on :mod:`chumicro_sockets` (TCP + TLS) and :mod:`chumicro_timing`
(ticks).  No async, no threads — Decision 0014's runner pattern:
both :class:`WebSocketClient` and :class:`WebSocketServer` satisfy
``check(now_ms) -> bool`` + ``handle(now_ms)``.  The canonical
promise (Decision 0045): an LED can keep blinking on the same board
through the opening handshake, frame I/O, control-frame interleave,
and the close handshake.

Slice 1 of Decision 0045 ships the wire-format primitives — URL
parser, opening-handshake encoders / parsers (both directions), the
streaming :class:`FrameParser`, the :func:`encode_frame` encoder,
the close-payload codec, and the exception hierarchy.  The
:class:`WebSocketClient` and :class:`WebSocketServer` orchestrators
land in slices 2 + 3.
"""

from chumicro_websockets._wire import (
    CLOSE_ABNORMAL,
    CLOSE_BAD_DATA,
    CLOSE_GOING_AWAY,
    CLOSE_INTERNAL_ERROR,
    CLOSE_MISSING_EXTN,
    CLOSE_NO_STATUS_RCVD,
    CLOSE_NORMAL,
    CLOSE_POLICY_VIOLATION,
    CLOSE_PROTOCOL_ERROR,
    CLOSE_TLS_HANDSHAKE,
    CLOSE_TOO_BIG,
    CLOSE_UNSUPPORTED_DATA,
    CONTROL_OPCODES,
    DATA_OPCODES,
    DEFAULT_CLOSE_TIMEOUT_MS,
    DEFAULT_HANDSHAKE_TIMEOUT_MS,
    DEFAULT_MAX_MESSAGE_BYTES,
    DEFAULT_MAX_TX_QUEUE_SIZE,
    DEFAULT_PONG_TIMEOUT_MS,
    DEFAULT_RECV_BUDGET_PER_TICK,
    DEFAULT_SEND_BUDGET_PER_TICK,
    MAX_CONTROL_PAYLOAD_BYTES,
    OPCODE_BINARY,
    OPCODE_CLOSE,
    OPCODE_CONTINUATION,
    OPCODE_PING,
    OPCODE_PONG,
    OPCODE_TEXT,
    RESERVED_CLOSE_CODES,
    WS_MAGIC_GUID,
    WS_VERSION,
    CaseInsensitiveDict,
    FrameParser,
    FrameParseState,
    HandshakeParseState,
    HandshakeRequestParser,
    HandshakeResponseParser,
    WebSocketBackpressureError,
    WebSocketError,
    WebSocketHandshakeError,
    WebSocketOversizedError,
    WebSocketProtocolError,
    WebSocketState,
    WebSocketStateError,
    WebSocketTimeoutError,
    WebSocketURLError,
    derive_accept_key,
    encode_client_handshake,
    encode_close_payload,
    encode_frame,
    encode_server_handshake_response,
    encode_server_rejection,
    make_mask_key,
    make_websocket_key,
    parse_close_payload,
    parse_ws_url,
    validate_text_payload,
)

__all__ = [
    "CLOSE_ABNORMAL",
    "CLOSE_BAD_DATA",
    "CLOSE_GOING_AWAY",
    "CLOSE_INTERNAL_ERROR",
    "CLOSE_MISSING_EXTN",
    "CLOSE_NO_STATUS_RCVD",
    "CLOSE_NORMAL",
    "CLOSE_POLICY_VIOLATION",
    "CLOSE_PROTOCOL_ERROR",
    "CLOSE_TLS_HANDSHAKE",
    "CLOSE_TOO_BIG",
    "CLOSE_UNSUPPORTED_DATA",
    "CONTROL_OPCODES",
    "DATA_OPCODES",
    "DEFAULT_CLOSE_TIMEOUT_MS",
    "DEFAULT_HANDSHAKE_TIMEOUT_MS",
    "DEFAULT_MAX_MESSAGE_BYTES",
    "DEFAULT_MAX_TX_QUEUE_SIZE",
    "DEFAULT_PONG_TIMEOUT_MS",
    "DEFAULT_RECV_BUDGET_PER_TICK",
    "DEFAULT_SEND_BUDGET_PER_TICK",
    "MAX_CONTROL_PAYLOAD_BYTES",
    "OPCODE_BINARY",
    "OPCODE_CLOSE",
    "OPCODE_CONTINUATION",
    "OPCODE_PING",
    "OPCODE_PONG",
    "OPCODE_TEXT",
    "RESERVED_CLOSE_CODES",
    "WS_MAGIC_GUID",
    "WS_VERSION",
    "CaseInsensitiveDict",
    "FrameParser",
    "FrameParseState",
    "HandshakeParseState",
    "HandshakeRequestParser",
    "HandshakeResponseParser",
    "WebSocketBackpressureError",
    "WebSocketError",
    "WebSocketHandshakeError",
    "WebSocketOversizedError",
    "WebSocketProtocolError",
    "WebSocketState",
    "WebSocketStateError",
    "WebSocketTimeoutError",
    "WebSocketURLError",
    "derive_accept_key",
    "encode_client_handshake",
    "encode_close_payload",
    "encode_frame",
    "encode_server_handshake_response",
    "encode_server_rejection",
    "make_mask_key",
    "make_websocket_key",
    "parse_close_payload",
    "parse_ws_url",
    "validate_text_payload",
]
