site_name: chumicro-compat
site_url: https://chumicro.github.io/ChuMicro/compat/
theme:
  name: material
  palette:
    scheme: default

extra:
  version:
    provider: mike
    default:
      - stable
      - experimental

nav:
  - Guide: guide.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            show_source: false
            show_root_heading: true
            members_order: source
