site_name: chumicro-msgpack
site_url: https://chumicro.github.io/ChuMicro/msgpack/
repo_url: https://github.com/ChuMicro/ChuMicro/tree/develop/libraries/msgpack
repo_name: Source
theme:
  name: material
  palette:
    scheme: default
    primary: deep purple
    accent: purple
  icon:
    repo: fontawesome/brands/github

extra:
  version:
    provider: mike
    default:
      - stable
      - experimental
  homepage: https://chumicro.github.io/ChuMicro/


nav:
  - Home: index.md
  - Guide: guide.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            show_source: false
            show_root_heading: true
            members_order: source
