"""Tests for ide.py — IDE configuration generation."""

import json
from xml.etree import ElementTree

from ide_sync import _config_filename, sync_ide


class TestConfigFilename:
    """Tests for _config_filename."""

    def test_simple_name(self):
        """Simple name is converted to XML filename."""
        assert _config_filename("Lint") == "Lint.xml"

    def test_spaces_become_underscores(self):
        """Spaces in names are replaced with underscores."""
        assert _config_filename("Check API") == "Check_API.xml"

    def test_multi_word(self):
        """Multi-word names are fully converted."""
        assert _config_filename("Test Libraries Functional") == "Test_Libraries_Functional.xml"


class TestSyncIde:
    """Tests for sync_ide — integration with real workspace."""

    def test_idempotent(self):
        """Running sync_ide twice produces the same result."""
        result1 = sync_ide()
        assert result1 == 0
        result2 = sync_ide()
        assert result2 == 0

    def test_creates_pyrightconfig(self):
        """pyrightconfig.json exists after sync."""
        from workspace import ROOT

        sync_ide()
        config_file = ROOT / "pyrightconfig.json"
        assert config_file.exists()
        config = json.loads(config_file.read_text())
        assert "extraPaths" in config
        assert len(config["extraPaths"]) > 0

    def test_creates_vscode_tasks(self):
        """VS Code tasks.json exists after sync."""
        from workspace import ROOT

        sync_ide()
        tasks_file = ROOT / ".vscode" / "tasks.json"
        assert tasks_file.exists()
        tasks = json.loads(tasks_file.read_text())
        assert tasks["version"] == "2.0.0"
        assert len(tasks["tasks"]) > 0

    def test_creates_pycharm_configs(self):
        """PyCharm run configurations are created."""
        from workspace import ROOT

        sync_ide()
        config_dir = ROOT / ".idea" / "runConfigurations"
        assert config_dir.is_dir()
        xml_files = list(config_dir.glob("*.xml"))
        assert len(xml_files) > 0

    def test_generated_iml_includes_reset_guidance(self):
        """The generated .iml should explain how to reset local PyCharm rewrites."""
        from workspace import ROOT

        sync_ide()
        iml_file = ROOT / ".idea" / "chumicro.iml"
        assert iml_file.exists()
        content = iml_file.read_text()
        ElementTree.fromstring(content)
        assert "Generated by scripts/run.py sync-ide." in content
        assert "PyCharm may rewrite this file" in content
        assert "python scripts/run.py sync-ide" in content

    def test_preserves_existing_misc_xml(self, tmp_path, monkeypatch):
        """sync_ide should never overwrite an existing .idea/misc.xml."""
        import ide_sync

        fake_root = tmp_path
        (fake_root / ".idea").mkdir()
        misc_file = fake_root / ".idea" / "misc.xml"
        original = "<project version=\"4\"><!-- user content --></project>\n"
        misc_file.write_text(original)

        monkeypatch.setattr(ide_sync, "ROOT", fake_root)
        ide_sync._sync_pycharm_misc_xml()

        assert misc_file.read_text() == original

    def test_creates_misc_xml_when_missing(self, tmp_path, monkeypatch):
        """sync_ide should seed misc.xml with a PyCharm-convention SDK name."""
        import ide_sync

        fake_root = tmp_path / "chumicro"
        fake_root.mkdir()
        (fake_root / ".idea").mkdir()

        monkeypatch.setattr(ide_sync, "ROOT", fake_root)
        ide_sync._sync_pycharm_misc_xml()

        misc_file = fake_root / ".idea" / "misc.xml"
        assert misc_file.exists()
        content = misc_file.read_text()
        ElementTree.fromstring(content)
        # Name follows PyCharm's convention: Python X.Y (<project folder>)
        assert "(chumicro)" in content
        assert "project-jdk-name=" in content
