"""Load and validate device configuration for device testing.

Two user-local config files (both gitignored):

- ``devices.yml`` — device registry (board connections, serial addresses,
  runtime type) and top-level defaults (active devices, deploy mode, IDE
  runtime preference).  Generated by ``python scripts/run.py setup``.
- ``device-config.yml`` — shared test environment (WiFi, MQTT, etc.).
  Generated by ``python scripts/run.py setup``.

Environment variable overrides: ``CHUMICRO_DEVICES`` and
``CHUMICRO_DEVICE_CONFIG``.

See Decision 0027 for the full schema.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path

import yaml
from chumicro_deploy.config.default import load_raw_entries

#: Default filename for the device registry — looked up relative to the
#: workspace root passed in by the caller (or ``Path.cwd()`` when no
#: root is given).  Kept as a filename rather than an absolute path so
#: the module has no compile-time dependency on ChuMicro's repo
#: layout — simplifies the future ``chumicro-deploy`` extraction
#: (Decision 0028).
DEFAULT_DEVICES_FILENAME = "devices.yml"
#: Default filename for the shared test environment config.
DEFAULT_DEVICE_CONFIG_FILENAME = "device-config.yml"

#: Required fields for each device entry in devices.yml.
_REQUIRED_DEVICE_FIELDS = ("id", "runtime", "address")
#: Allowed runtime values.
_VALID_RUNTIMES = ("micropython", "circuitpython")
#: Allowed deploy mode values.
_VALID_DEPLOY_MODES = ("ram", "flash")
#: Allowed ide_runtime values.
_VALID_IDE_RUNTIMES = ("micropython", "circuitpython", "both")


@dataclass
class DeviceEntry:
    """A single device from the device registry."""

    identifier: str
    runtime: str
    address: str
    description: str = ""
    connection_type: str = "serial"
    serial_baudrate: int = 115200
    deploy_mode: str = "ram"
    circuitpy_drive_path: str | None = None
    setup_command: str | None = None
    extra: dict = field(default_factory=dict)


@dataclass
class DeviceDefaults:
    """Top-level defaults from the ``defaults:`` section of ``devices.yml``.

    Controls which devices are targeted from IDE play buttons, the
    default deploy mode for all devices, and which runtimes the
    IDE targets.
    """

    micropython: str | None = None
    circuitpython: str | None = None
    deploy_mode: str = "ram"
    ide_runtime: str = "micropython"


class DeviceConfigError(Exception):
    """Raised when device configuration is missing or invalid."""


def _resolve_path(
    environment_variable: str,
    default_filename: str,
    workspace_root: Path | None = None,
) -> Path:
    """Resolve a config file path from an environment variable or default.

    Args:
        environment_variable: Name of the environment variable to check.
        default_filename: Filename to look up under *workspace_root*
            when the variable is unset.
        workspace_root: Directory that contains the config file.
            Defaults to :func:`Path.cwd`.
    """
    override = os.environ.get(environment_variable)
    if override:
        return Path(override)
    root = workspace_root if workspace_root is not None else Path.cwd()
    return root / default_filename


def _load_yaml(path: Path) -> dict:
    """Load and return a YAML file as a dict.

    Args:
        path: Path to the YAML file.

    Raises:
        DeviceConfigError: If the file is missing or not valid YAML.
    """
    if not path.exists():
        raise DeviceConfigError(
            f"Config file not found: {path}\n"
            f"Run 'python scripts/run.py setup' to generate it."
        )
    with path.open() as config_file:
        data = yaml.safe_load(config_file)
    if not isinstance(data, dict):
        raise DeviceConfigError(
            f"Expected a YAML mapping in {path}, got {type(data).__name__}"
        )
    return data


def _parse_defaults(raw: dict) -> DeviceDefaults:
    """Parse and validate the ``defaults:`` section of ``devices.yml``.

    Args:
        raw: Raw dict from the YAML defaults section (may be empty).

    Returns:
        Validated DeviceDefaults.

    Raises:
        DeviceConfigError: If values are invalid.
    """
    deploy_mode = raw.get("deploy_mode", "ram")
    if deploy_mode not in _VALID_DEPLOY_MODES:
        raise DeviceConfigError(
            f"Invalid deploy_mode '{deploy_mode}' in defaults, "
            f"must be one of {_VALID_DEPLOY_MODES}"
        )
    ide_runtime = raw.get("ide_runtime", "micropython")
    if ide_runtime not in _VALID_IDE_RUNTIMES:
        raise DeviceConfigError(
            f"Invalid ide_runtime '{ide_runtime}' in defaults, "
            f"must be one of {_VALID_IDE_RUNTIMES}"
        )
    return DeviceDefaults(
        micropython=raw.get("micropython"),
        circuitpython=raw.get("circuitpython"),
        deploy_mode=deploy_mode,
        ide_runtime=ide_runtime,
    )


def _validate_device(raw: dict, index: int, *, global_deploy_mode: str = "ram") -> DeviceEntry:
    """Validate a single device entry and return a DeviceEntry.

    Args:
        raw: Raw dict from the YAML devices list.
        index: Position in the list (for error messages).
        global_deploy_mode: Default deploy mode from the ``defaults:``
            section, used when the device entry omits ``deploy_mode``.

    Raises:
        DeviceConfigError: If required fields are missing or values are invalid.
    """
    missing = [
        field_name for field_name in _REQUIRED_DEVICE_FIELDS
        if field_name not in raw
    ]
    if missing:
        raise DeviceConfigError(
            f"Device entry {index}: missing required fields: {', '.join(missing)}"
        )

    runtime = raw["runtime"]
    if runtime not in _VALID_RUNTIMES:
        raise DeviceConfigError(
            f"Device entry {index} ({raw['id']}): "
            f"invalid runtime '{runtime}', must be one of {_VALID_RUNTIMES}"
        )

    if "deploy_mode" in raw and raw["deploy_mode"] not in _VALID_DEPLOY_MODES:
        raise DeviceConfigError(
            f"Device entry {index} ({raw['id']}): "
            f"invalid deploy_mode '{raw['deploy_mode']}', "
            f"must be one of {_VALID_DEPLOY_MODES}"
        )

    # Extract known fields, put everything else in extra.
    known_keys = {
        "id", "runtime", "address", "description", "connection_type",
        "serial_baudrate", "deploy_mode",
        "circuitpy_drive_path", "setup_command",
    }
    extra = {key: value for key, value in raw.items() if key not in known_keys}

    return DeviceEntry(
        identifier=raw["id"],
        runtime=runtime,
        address=raw["address"],
        description=raw.get("description", ""),
        connection_type=raw.get("connection_type", "serial"),
        serial_baudrate=raw.get("serial_baudrate", 115200),
        deploy_mode=raw.get("deploy_mode", global_deploy_mode),
        circuitpy_drive_path=raw.get("circuitpy_drive_path"),
        setup_command=raw.get("setup_command"),
        extra=extra,
    )


def load_device_registry(
    path: Path | None = None,
    *,
    workspace_root: Path | None = None,
) -> tuple[list[DeviceEntry], DeviceDefaults]:
    """Load and validate the device registry with defaults.

    Reads ``devices.yml`` and parses both the ``defaults:`` section
    and the ``devices:`` list.  The global ``deploy_mode`` from
    defaults is applied to any device entry that does not specify
    its own.

    Args:
        path: Explicit path to devices.yml.  When ``None``, checks
            ``CHUMICRO_DEVICES`` then falls back to ``workspace_root /
            devices.yml`` (or ``Path.cwd() / devices.yml`` when no
            workspace root is given).
        workspace_root: Directory that contains ``devices.yml``.  When
            ``None``, defaults to :func:`Path.cwd`.

    Returns:
        Tuple of ``(devices, defaults)``.

    Raises:
        DeviceConfigError: If the file is missing, invalid, or contains
            entries with missing required fields.
    """
    resolved = path or _resolve_path(
        "CHUMICRO_DEVICES", DEFAULT_DEVICES_FILENAME, workspace_root,
    )
    try:
        entries, raw_defaults = load_raw_entries(resolved)
    except FileNotFoundError as error:
        raise DeviceConfigError(
            f"Config file not found: {resolved}\n"
            "Run 'python scripts/run.py setup' to generate it."
        ) from error
    except (yaml.YAMLError, ValueError) as error:
        raise DeviceConfigError(str(error)) from error

    if not entries:
        raise DeviceConfigError(f"Expected a 'devices' list in {resolved}")

    defaults = _parse_defaults(raw_defaults)
    return (
        [
            _validate_device(entry, index, global_deploy_mode=defaults.deploy_mode)
            for index, entry in enumerate(entries)
        ],
        defaults,
    )


def load_devices(
    path: Path | None = None,
    *,
    workspace_root: Path | None = None,
) -> list[DeviceEntry]:
    """Load and validate the device registry.

    Convenience wrapper around :func:`load_device_registry` that
    returns only the device list.  Global ``deploy_mode`` from the
    ``defaults:`` section is applied to device entries.

    Args:
        path: Explicit path to devices.yml.  When ``None``, checks
            ``CHUMICRO_DEVICES`` then falls back to the workspace default.
        workspace_root: Directory that contains ``devices.yml``.  When
            ``None``, defaults to :func:`Path.cwd`.

    Returns:
        List of validated DeviceEntry objects.

    Raises:
        DeviceConfigError: If the file is missing, invalid, or contains
            entries with missing required fields.
    """
    devices, _defaults = load_device_registry(path, workspace_root=workspace_root)
    return devices


def load_device_config(
    path: Path | None = None,
    *,
    workspace_root: Path | None = None,
) -> dict:
    """Load the shared test environment configuration.

    Args:
        path: Explicit path to device-config.yml.  When ``None``, checks
            ``CHUMICRO_DEVICE_CONFIG`` then falls back to the workspace
            default.
        workspace_root: Directory that contains ``device-config.yml``.
            When ``None``, defaults to :func:`Path.cwd`.

    Returns:
        Dict of environment configuration (WiFi, MQTT, NTP, etc.).

    Raises:
        DeviceConfigError: If the file is missing or not valid YAML.
    """
    resolved = path or _resolve_path(
        "CHUMICRO_DEVICE_CONFIG", DEFAULT_DEVICE_CONFIG_FILENAME, workspace_root,
    )
    return _load_yaml(resolved)


def filter_devices(
    devices: list[DeviceEntry],
    *,
    runtime: str | None = None,
    device_id: str | None = None,
) -> list[DeviceEntry]:
    """Filter a device list by runtime and/or device ID.

    Args:
        devices: Full list of devices.
        runtime: Filter to devices matching this runtime.
        device_id: Filter to the device with this ID.

    Returns:
        Filtered list of DeviceEntry objects.
    """
    result = devices
    if runtime:
        result = [device for device in result if device.runtime == runtime]
    if device_id:
        result = [device for device in result if device.identifier == device_id]
    return result


def resolve_ide_devices(
    devices: list[DeviceEntry],
    defaults: DeviceDefaults,
) -> list[DeviceEntry]:
    """Return the devices to target for IDE play-button tests.

    Uses the ``defaults:`` section of ``devices.yml`` to determine
    which devices to target based on ``ide_runtime``.  For each
    runtime, the device whose ID matches the ``micropython`` or
    ``circuitpython`` field in defaults is selected.  If no ID is
    configured, the first device of that runtime is used.

    Args:
        devices: Full list of devices from the registry.
        defaults: Parsed defaults section.

    Returns:
        List of devices to target (one per active runtime).
    """
    runtimes_to_target: list[str] = []
    if defaults.ide_runtime in ("micropython", "both"):
        runtimes_to_target.append("micropython")
    if defaults.ide_runtime in ("circuitpython", "both"):
        runtimes_to_target.append("circuitpython")

    result: list[DeviceEntry] = []
    for runtime in runtimes_to_target:
        target_id = getattr(defaults, runtime, None)
        if target_id:
            for device in devices:
                if device.identifier == target_id:
                    result.append(device)
                    break
        else:
            for device in devices:
                if device.runtime == runtime:
                    result.append(device)
                    break

    return result
