"""Generate the FAQ page's FAQPage JSON-LD from its own prose.

Search engines and answer engines read `FAQPage` markup to lift a
question and its answer directly.  Writing that markup by hand next to
the prose it repeats guarantees the two drift, so this script derives
it from the page: every ``##`` heading is a question, and the prose
under it is the answer.

Usage::

    python scripts/faq_schema.py            # rewrite the block in place
    python scripts/faq_schema.py --check    # fail when it is stale

``scripts/tests/test_faq_schema.py`` runs the check, so a PR that edits
the questions without regenerating fails preflight rather than
publishing markup that contradicts the page.
"""

from __future__ import annotations

import argparse
import json
import re
import sys

from repo_layout import ROOT

#: The page the markup describes.
FAQ_SOURCE = ROOT / "docs" / "faq.md"

#: Where the page is published.
FAQ_URL = "https://chumicro.com/ChuMicro/guides/faq/"

#: The generated block sits between these markers, so a rewrite replaces
#: only what it owns.
START_MARKER = "<!-- faq-schema: generated by scripts/faq_schema.py -->"
END_MARKER = "<!-- /faq-schema -->"

#: Inline markdown that adds nothing to a spoken answer.
_LINK = re.compile(r"\[([^\]]+)\]\([^)]+\)")
_CODE = re.compile(r"`([^`]+)`")
_BOLD = re.compile(r"\*\*([^*]+)\*\*")


def _plain_text(markdown: str) -> str:
    """Return *markdown* as the sentence a person would read aloud."""
    text = _LINK.sub(r"\1", markdown)
    text = _BOLD.sub(r"\1", text)
    text = _CODE.sub(r"\1", text)
    return " ".join(text.split())


def _without_schema(page: str) -> str:
    """Return *page* with any previously generated block removed.

    Parsing has to see the prose alone, so that generating twice in a
    row produces the same file and ``--check`` means what it says.
    """
    if START_MARKER not in page or END_MARKER not in page:
        return page
    start = page.index(START_MARKER)
    end = page.index(END_MARKER) + len(END_MARKER)
    return page[:start] + page[end:]


def parse_questions(page: str) -> list[tuple[str, str]]:
    """Return ``(question, answer)`` for each ``##`` section of *page*.

    The answer is the prose before the first code block, which is the
    part that answers the question in words.  Code belongs on the page,
    not in a search result.
    """
    sections = re.split(r"^## ", _without_schema(page), flags=re.MULTILINE)[1:]
    questions: list[tuple[str, str]] = []
    for section in sections:
        heading, _, rest = section.partition("\n")
        prose_parts: list[str] = []
        for paragraph in rest.split("\n\n"):
            stripped = paragraph.strip()
            if not stripped or stripped.startswith(("```", "- ", "| ")):
                if prose_parts:
                    break
                continue
            prose_parts.append(_plain_text(stripped))
            if len(prose_parts) == 2:
                break
        if prose_parts:
            questions.append((heading.strip(), " ".join(prose_parts)))
    return questions


def build_schema(questions: list[tuple[str, str]]) -> str:
    """Return the JSON-LD block for *questions*."""
    payload = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "url": FAQ_URL,
        "mainEntity": [
            {
                "@type": "Question",
                "name": question,
                "acceptedAnswer": {"@type": "Answer", "text": answer},
            }
            for question, answer in questions
        ],
    }
    body = json.dumps(payload, indent=2)
    return (
        f"{START_MARKER}\n"
        f'<script type="application/ld+json">\n{body}\n</script>\n'
        f"{END_MARKER}"
    )


def render(page: str) -> str:
    """Return *page* with its schema block current."""
    schema = build_schema(parse_questions(page))
    if START_MARKER in page:
        start = page.index(START_MARKER)
        end = page.index(END_MARKER) + len(END_MARKER)
        return page[:start] + schema + page[end:]
    return page.rstrip("\n") + "\n\n" + schema + "\n"


def main(argv: list[str] | None = None) -> int:
    """Rewrite the block, or report that it is stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="Exit 1 when the block does not match the page's questions.",
    )
    arguments = parser.parse_args(argv)

    page = FAQ_SOURCE.read_text()
    rendered = render(page)
    if arguments.check:
        if rendered != page:
            print(
                "FAQ schema is stale.  Run `python scripts/faq_schema.py` "
                "and commit the result.",
                file=sys.stderr,
            )
            return 1
        print("FAQ schema matches the page.")
        return 0

    FAQ_SOURCE.write_text(rendered)
    print(f"FAQ schema written: {len(parse_questions(page))} questions.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
