"""Render the wiring and debounce schematics for the chumicro-buttons guide.

Five SVGs land in ``libraries/buttons/docs/schematics/``:

* ``wiring-active-low.svg`` — a momentary switch to GND with the pin's own
  pull-up, which is what ``active_low=True`` (the default) expects.
* ``wiring-active-high.svg`` — a switch to 3V3 with an external pull-down,
  which is what ``active_low=False`` expects.
* ``debounce-rc.svg`` — the RC low-pass on its own, including the series
  resistor that keeps the discharge path finite.
* ``debounce-rc-schmitt.svg`` — an RC network through a 74HC14, which is the
  first arrangement clean enough for ``settle_ms=0``.
* ``debounce-spdt-latch.svg`` — an SPDT switch and a 74HC00 RS latch, the
  arrangement with no bounce to filter at all.

Run::

    python scripts/render_button_schematics.py            # all five
    python scripts/render_button_schematics.py --figure debounce-rc

``schemdraw`` is a host-only documentation tool.  It belongs in the
workspace virtualenv (``uv pip install schemdraw``) and in no library's
``pyproject.toml``: nothing it produces ships to a device.  Preflight does
not run this script for that reason, so re-run it by hand after editing a
figure and commit the SVG alongside the change.

Colors: one mid-tone slate ink for every stroke and every label.  The
documentation site renders these on a dark background and GitHub renders
them on a light one, and an ``<img>`` inherits neither page's colors, so
the ink has to carry about 4:1 contrast against both ends.
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

import schemdraw
from schemdraw import elements as elm
from schemdraw import logic

REPO_ROOT = Path(__file__).resolve().parent.parent
# docs/img/ is regenerated by the docs build from support/docs/, so hand-authored
# figures live in a sibling directory that git actually tracks.
OUT_DIR = REPO_ROOT / "libraries" / "buttons" / "docs" / "schematics"

#: Mid-tone slate: ~3.5:1 on white, ~4.6:1 on the Material slate background.
INK = "#7f8a96"

UNIT = 2.0
LINE_WIDTH = 1.7
LABEL_SIZE = 13
NOTE_SIZE = 11
NOTE_STEP = 0.52

# ---------------------------------------------------------------------------
# The RC numbers
#
# Both RC figures hang the same pull-up and the same capacitor off 3V3 and
# differ only in the series resistor, because the two figures load the RC
# node with different things.  Kilohms times microfarads land in
# milliseconds, so every time constant below is a product of the values as
# they are printed on the drawing.
# ---------------------------------------------------------------------------

SUPPLY_VOLTS = 3.3

#: Pull-up on both RC figures.  Ten kilohms holds the released node at 3V3
#: against pin leakage while costing 330 µA when the button is down.
RC_PULL_UP_KOHM = 10.0

#: Capacitor on both RC figures.  A microfarad-class part is what puts the
#: press edge in the same range as contact bounce; the nanofarad values the
#: tutorials print leave that edge unfiltered.
RC_CAPACITOR_UF = 2.2

#: Series resistor for the bare-pin figure.  It divides against whatever
#: pull-up holds the node up, and a pin's own pull-up can be as low as
#: ``WEAKEST_INTERNAL_PULL_UP_KOHM``, so it has to stay small.
RC_SERIES_PLAIN_KOHM = 2.2

#: Series resistor for the 74HC14 figure.  A logic input has no pull-up to
#: divide against, so this one is free to move up toward R1, which narrows
#: the gap between the two time constants and gentles the contacts.
RC_SERIES_SCHMITT_KOHM = 4.7

#: Weakest internal pull-up a CircuitPython board is likely to hand you.
#: The nRF52840 sits near 13 kΩ; an RP2040 is nearer 50 kΩ, which is kinder.
#: The library turns a pull on for every button, so the low end is what a
#: series resistor has to survive.
WEAKEST_INTERNAL_PULL_UP_KOHM = 13.0

#: Highest voltage a 3.3 V logic input is still guaranteed to read as low,
#: which is the usual 0.3 × VDD.
LOGIC_LOW_CEILING_VOLTS = 0.3 * SUPPLY_VOLTS

#: 74HC14 switching points at 3.3 V, interpolated from the typical curves in
#: the Nexperia datasheet.  A rising input has to pass the upper one before
#: the output flips low; a falling input has to pass the lower one before it
#: flips back.  The gap between them is the hysteresis the figure relies on.
SCHMITT_UPPER_VOLTS = 1.8
SCHMITT_LOWER_VOLTS = 1.05


def _drawing() -> schemdraw.Drawing:
    """Return an empty drawing carrying the house style."""
    schemdraw.use("svg")
    drawing = schemdraw.Drawing()
    drawing.config(
        unit=UNIT,
        fontsize=LABEL_SIZE,
        font="Arial",
        color=INK,
        lw=LINE_WIDTH,
        # Elements that fill a shape with "the background" -- switch
        # contacts, open terminals -- resolve it to this.  Leaving it
        # transparent keeps them hollow on a light page and a dark one.
        bgcolor="none",
    )
    return drawing


def _text(
    drawing: schemdraw.Drawing,
    xy: tuple[float, float],
    text: str,
    *,
    halign: str = "left",
    valign: str = "center",
    size: float = NOTE_SIZE,
) -> None:
    """Place one line of free text at *xy*."""
    drawing.add(
        elm.Label().at(xy).label(text, halign=halign, valign=valign, fontsize=size)
    )


def _notes(
    drawing: schemdraw.Drawing,
    xy: tuple[float, float],
    lines: list[str],
    *,
    size: float = NOTE_SIZE,
    step: float = NOTE_STEP,
) -> None:
    """Place a left-aligned block of notes, one drawn label per line.

    schemdraw centers the continuation lines of a multi-line label, so a
    block that has to align on its left edge is drawn a line at a time.
    """
    left, top = xy
    for index, line in enumerate(lines):
        _text(drawing, (left, top - index * step), line, halign="left", valign="top", size=size)


def _gpio_terminal(
    drawing: schemdraw.Drawing,
    xy: tuple[float, float],
    text: str = "GPIO",
) -> None:
    """Mark where the wire meets the microcontroller pin."""
    drawing.add(elm.Dot(open=True).at(xy))
    _text(drawing, (xy[0] + 0.2, xy[1] + 0.18), text, halign="left", valign="bottom", size=LABEL_SIZE)


# ---------------------------------------------------------------------------
# 1. Active low, internal pull-up
# ---------------------------------------------------------------------------


def wiring_active_low(path: Path) -> None:
    """Momentary switch to GND, pull-up supplied by the pin itself."""
    drawing = _drawing()

    # The pull-up and the rail it hangs off are drawn dashed because they
    # are already inside the chip -- there is no part to buy here.
    drawing.add(elm.Vdd().at((0, 5.6)).label("3V3").linestyle("--"))
    drawing.add(
        elm.Resistor()
        .at((0, 5.6))
        .to((0, 3.8))
        .linestyle("--")
        .label("internal pull-up\n(tens of kΩ)", loc="top")
    )
    # .right() resets the direction the resistor left behind: a Rect drawn
    # with the pen still pointing down comes out rotated a quarter turn.
    drawing.add(elm.Rect(corner1=(-3.3, 3.0), corner2=(1.7, 6.6), ls="--").at((0, 0)).right())
    _text(drawing, (-0.8, 2.75), "inside the microcontroller", halign="center", valign="top")

    drawing.add(elm.Line().at((0, 3.8)).to((4.6, 3.8)))
    _text(drawing, (1.95, 3.98), "GPIO", halign="left", valign="bottom", size=LABEL_SIZE)

    drawing.add(elm.Button().at((4.6, 3.8)).to((4.6, 2.3)).label("SW1\nmomentary", loc="bot"))
    drawing.add(elm.Line().at((4.6, 2.3)).to((4.6, 1.8)))
    drawing.add(elm.Ground().at((4.6, 1.8)))

    _notes(
        drawing,
        (-3.3, 0.35),
        [
            "Released: the pull-up holds the pin at 3V3, so the pin reads HIGH.",
            "Pressed: the switch ties the pin to 0 V, so the pin reads LOW.",
            "This is Button(pin, active_low=True), the default. Add no resistor.",
            "Bare contacts bounce: leave settle_ms at 20.",
        ],
    )
    drawing.save(str(path), transparent=True)


# ---------------------------------------------------------------------------
# 2. Active high, external pull-down
# ---------------------------------------------------------------------------


def wiring_active_high(path: Path) -> None:
    """Momentary switch to 3V3, held low by an external 10 k resistor."""
    drawing = _drawing()

    drawing.add(elm.Vdd().at((0, 6.6)).label("3V3"))
    drawing.add(elm.Button().at((0, 6.6)).to((0, 4.7)).label("SW1\nmomentary", loc="top"))
    drawing.add(elm.Line().at((0, 4.7)).to((0, 4.0)))
    drawing.add(elm.Dot().at((0, 4.0)))

    drawing.add(elm.Resistor().at((0, 4.0)).to((0, 2.5)).label("R1\n10 kΩ\npull-down", loc="top"))
    drawing.add(elm.Line().at((0, 2.5)).to((0, 2.0)))
    drawing.add(elm.Ground().at((0, 2.0)))

    drawing.add(elm.Line().at((0, 4.0)).to((3.6, 4.0)))
    _gpio_terminal(drawing, (3.6, 4.0))

    _notes(
        drawing,
        (-2.4, 0.5),
        [
            "Released: R1 drains the pin to 0 V, so the pin reads LOW.",
            "Pressed: the switch puts 3V3 on the pin, so the pin reads HIGH.",
            "This is Button(pin, active_low=False).",
            "R1 is not optional. Without it the pin floats when the button is up",
            "and reads whatever the last stray charge left behind.",
            "Holding the button draws 3.3 V / 10 kΩ = 330 µA.",
        ],
    )
    drawing.save(str(path), transparent=True)


# ---------------------------------------------------------------------------
# 3. RC low-pass
# ---------------------------------------------------------------------------


def _number(value: float) -> str:
    """Render a component value the way it is printed on a part: 10, not 10.0."""
    return f"{value:g}"


def _milliseconds(value: float) -> str:
    """Render a time constant to two significant figures."""
    return f"{value:.1f}" if value < 10 else f"{value:.0f}"


def _press_time_constant_ms(series_kohm: float) -> float:
    """Return how fast the capacitor empties when the switch closes.

    Closing the switch pins the top of the series resistor to 0 V, so the
    capacitor's only way out is that resistor.  The pull-up is on the far
    side of the closed contacts and takes no part in it.
    """
    return series_kohm * RC_CAPACITOR_UF


def _release_time_constant_ms(series_kohm: float) -> float:
    """Return how fast the capacitor refills when the switch opens.

    Opening the switch leaves the capacitor to charge from 3V3 through the
    pull-up and the series resistor in line, so this constant is always the
    larger of the pair.  That gap is what no amount of value-picking removes.
    """
    return (RC_PULL_UP_KOHM + series_kohm) * RC_CAPACITOR_UF


def _ramp_ms(
    time_constant_ms: float,
    start_volts: float,
    settling_volts: float,
    target_volts: float,
) -> float:
    """Return how long an RC ramp takes to travel from *start* to *target*.

    Args:
        time_constant_ms: The constant governing this direction of travel.
        start_volts: Where the node sits when the ramp begins.
        settling_volts: Where the ramp would end if nothing interrupted it.
        target_volts: The threshold whose crossing time is wanted.
    """
    return time_constant_ms * math.log(
        (start_volts - settling_volts) / (target_volts - settling_volts)
    )


def _pressed_node_volts(series_kohm: float, pull_up_kohm: float) -> float:
    """Return what a pressed node settles at against an input's own pull-up.

    With the switch closed and no current left flowing into the capacitor,
    the series resistor and the input's pull-up are a plain divider across
    3V3.  A bare microcontroller pin brings a pull-up of its own to this;
    a logic gate's input brings none, and the node reaches a true 0 V.
    """
    return SUPPLY_VOLTS * series_kohm / (series_kohm + pull_up_kohm)


def _rc_front_end(
    drawing: schemdraw.Drawing, series_kohm: float
) -> tuple[float, float]:
    """Draw the pull-up, switch, series resistor and cap.

    Args:
        drawing: The figure being built.
        series_kohm: R2, the resistor between the switched node and the cap.

    Returns:
        The node the capacitor sits on, which is where the rest of the
        figure continues.
    """
    pull_up = _number(RC_PULL_UP_KOHM)
    drawing.add(elm.Vdd().at((0, 6.8)).label("3V3"))
    drawing.add(
        elm.Resistor().at((0, 6.8)).to((0, 4.8)).label(f"R1\n{pull_up} kΩ", loc="top")
    )
    drawing.add(elm.Dot().at((0, 4.8)))

    # Switch leg.
    drawing.add(elm.Line().at((0, 4.8)).to((0, 4.2)))
    drawing.add(elm.Button().at((0, 4.2)).to((0, 2.4)).label("SW1", loc="top"))
    drawing.add(elm.Line().at((0, 2.4)).to((0, 1.9)))
    drawing.add(elm.Ground().at((0, 1.9)))

    # Series leg into the capacitor.
    drawing.add(
        elm.Resistor()
        .at((0, 4.8))
        .to((2.4, 4.8))
        .label(f"R2\n{_number(series_kohm)} kΩ", loc="top")
    )
    drawing.add(elm.Line().at((2.4, 4.8)).to((3.4, 4.8)))
    drawing.add(elm.Dot().at((3.4, 4.8)))
    drawing.add(
        elm.Capacitor()
        .at((3.4, 4.8))
        .to((3.4, 3.0))
        .label(f"C1\n{_number(RC_CAPACITOR_UF)} µF", loc="bot")
    )
    drawing.add(elm.Line().at((3.4, 3.0)).to((3.4, 1.9)))
    drawing.add(elm.Ground().at((3.4, 1.9)))
    return (3.4, 4.8)


def _rc_arithmetic(series_kohm: float) -> tuple[str, str]:
    """Return the two time-constant lines shared by both RC figures."""
    capacitor = _number(RC_CAPACITOR_UF)
    charge_kohm = _number(RC_PULL_UP_KOHM + series_kohm)
    press_ms = _milliseconds(_press_time_constant_ms(series_kohm))
    release_ms = _milliseconds(_release_time_constant_ms(series_kohm))
    return (
        f"Press: C1 empties through R2 alone, τ = {_number(series_kohm)} kΩ"
        f" × {capacitor} µF = {press_ms} ms.",
        f"Release: C1 refills through R1 and R2 in line, τ = {charge_kohm} kΩ"
        f" × {capacitor} µF = {release_ms} ms.",
    )


def _contact_currents(series_kohm: float) -> tuple[str, str]:
    """Return what the closed contacts carry: the held current, then the peak.

    Holding the button down runs 3V3 through the pull-up and the contacts.
    The peak arrives an instant earlier, when the closing contacts hand the
    charged capacitor a path to ground through the series resistor.
    """
    held_ua = SUPPLY_VOLTS / RC_PULL_UP_KOHM * 1000
    peak_ma = SUPPLY_VOLTS / series_kohm
    return f"{held_ua:.0f} µA", f"{peak_ma:.2g} mA"


def debounce_rc(path: Path) -> None:
    """RC low-pass straight into the pin."""
    drawing = _drawing()
    series_kohm = RC_SERIES_PLAIN_KOHM
    node = _rc_front_end(drawing, series_kohm)

    drawing.add(elm.Line().at(node).to((6.2, 4.8)))
    _gpio_terminal(drawing, (6.2, 4.8))

    press_line, release_line = _rc_arithmetic(series_kohm)
    series = _number(series_kohm)
    pull_up = _number(RC_PULL_UP_KOHM)
    internal = _number(WEAKEST_INTERNAL_PULL_UP_KOHM)
    kept_low = _pressed_node_volts(series_kohm, WEAKEST_INTERNAL_PULL_UP_KOHM)
    lost_low = _pressed_node_volts(RC_PULL_UP_KOHM, WEAKEST_INTERNAL_PULL_UP_KOHM)
    held, peak = _contact_currents(series_kohm)
    fall_ms = _ramp_ms(
        _press_time_constant_ms(series_kohm), SUPPLY_VOLTS, 0.0, LOGIC_LOW_CEILING_VOLTS
    )

    _notes(
        drawing,
        (-2.6, 0.4),
        [
            press_line,
            release_line,
            "C1 refills through R1 and empties without it, so the release edge is always the",
            "slower one, and R2 has to stay well under R1: the pin's own pull-up is still on,",
            f"as little as {internal} kΩ, and R2 divides against it. At {series} kΩ the pressed"
            " pin sits",
            f"near {kept_low:.1f} V, a solid low; at {pull_up} kΩ it would sit near"
            f" {lost_low:.1f} V, which is not one.",
            f"Closed, the contacts carry {held} through R1 plus a {peak} peak as C1 empties",
            "through R2. Leave R2 out and nothing limits that peak, and the press edge that",
            "reaches the pin is the raw one the contacts made.",
            f"What this buys: the bouncing never reaches the pin, and the press edge takes"
            f" {fall_ms:.0f} ms to",
            "reach a valid low instead of arriving as fast as the metal moves. What it does",
            "not buy: one guaranteed edge, because a plain input has a single threshold and no",
            "hysteresis you can count on. Turn settle_ms down to 5 here, not to 0.",
        ],
    )
    drawing.save(str(path), transparent=True)


# ---------------------------------------------------------------------------
# 4. RC low-pass into a Schmitt-trigger inverter
# ---------------------------------------------------------------------------


def debounce_rc_schmitt(path: Path) -> None:
    """An RC network squared up by a 74HC14."""
    drawing = _drawing()
    series_kohm = RC_SERIES_SCHMITT_KOHM
    node = _rc_front_end(drawing, series_kohm)

    drawing.add(elm.Line().at(node).to((5.0, 4.8)))
    gate = drawing.add(logic.SchmittNot().anchor("in1").at((5.0, 4.8)))
    out = gate.absanchors["out"]
    _text(drawing, (5.15, 5.02), "1", halign="left", valign="bottom")
    _text(drawing, (out[0] - 0.12, out[1] + 0.22), "2", halign="right", valign="bottom")
    _text(drawing, (out[0] + 0.1, out[1] - 0.85), "U1  74HC14", halign="left", valign="top", size=LABEL_SIZE)

    drawing.add(elm.Line().at(out).to((out[0] + 1.5, out[1])))
    _gpio_terminal(drawing, (out[0] + 1.5, out[1]))

    # Supply pins of the 74HC14, drawn as the decoupling pair they need.
    supply_x = out[0] + 4.2
    drawing.add(elm.Vdd().at((supply_x, 7.0)).label("3V3"))
    drawing.add(
        elm.Capacitor()
        .at((supply_x, 7.0))
        .to((supply_x, 5.6))
        .label("C2\n100 nF", loc="bot")
    )
    drawing.add(elm.Line().at((supply_x, 5.6)).to((supply_x, 5.1)))
    drawing.add(elm.Ground().at((supply_x, 5.1)))
    _text(drawing, (supply_x - 0.25, 6.6), "pin 14", halign="right", valign="center")
    _text(drawing, (supply_x - 0.25, 5.45), "pin 7", halign="right", valign="center")
    _text(drawing, (supply_x, 4.05), "U1 supply", halign="center", valign="top", size=LABEL_SIZE)

    press_line, release_line = _rc_arithmetic(series_kohm)
    press_constant_ms = _press_time_constant_ms(series_kohm)
    release_constant_ms = _release_time_constant_ms(series_kohm)
    held, peak = _contact_currents(series_kohm)
    fall_ms = _ramp_ms(press_constant_ms, SUPPLY_VOLTS, 0.0, SCHMITT_LOWER_VOLTS)
    rise_ms = _ramp_ms(release_constant_ms, 0.0, SUPPLY_VOLTS, SCHMITT_UPPER_VOLTS)
    # A gap in the bouncing lets the node climb back off the lower switching
    # point.  Reaching the upper one would undo the crossing that just
    # happened, and this is how long a gap that would take.
    undo_ms = _ramp_ms(
        release_constant_ms, SCHMITT_LOWER_VOLTS, SUPPLY_VOLTS, SCHMITT_UPPER_VOLTS
    )

    _notes(
        drawing,
        (-2.6, 0.4),
        [
            press_line,
            release_line,
            "Same lopsided pair: C1 refills through R1 and empties without it. R2 can be larger",
            "here than on a bare pin, because a 74HC14 input has no pull-up to divide against",
            "and the pressed node reaches a true 0 V. A larger R2 narrows the gap between the two",
            f"constants and gentles the contacts: {held} through R1 plus a {peak} peak as C1"
            " empties.",
            f"The 74HC14 switches at {SCHMITT_UPPER_VOLTS} V on the way up and"
            f" {SCHMITT_LOWER_VOLTS} V on the way down. C1 needs",
            f"{fall_ms:.0f} ms to fall to the lower point and {rise_ms:.0f} ms to climb to the"
            " upper one, so the contacts",
            "have long stopped moving before either one is crossed, and a gap in the bouncing",
            f"would have to last {undo_ms:.0f} ms to undo a crossing. One press, one clean"
            " output edge:",
            "this is the wiring that earns settle_ms=0.",
            "The output is inverted: pressing SW1 pulls the RC node LOW, so the pin goes HIGH.",
            "Read it with Button(pin, active_low=False).",
            "Power U1 from the same 3V3 as the board. Tie its five unused inputs, pins 3, 5, 9,",
            "11 and 13, to GND, and keep C2 across pins 14 and 7 close to the chip.",
        ],
    )
    drawing.save(str(path), transparent=True)


# ---------------------------------------------------------------------------
# 5. SPDT switch into a cross-coupled NAND latch
# ---------------------------------------------------------------------------


def debounce_spdt_latch(path: Path) -> None:
    """SPDT switch, two 74HC00 gates, no bounce to filter."""
    drawing = _drawing()

    nand1 = drawing.add(logic.Nand().anchor("in1").at((5.4, 5.6)))
    nand2 = drawing.add(logic.Nand().anchor("in1").at((5.4, 2.2)))
    s_in = nand1.absanchors["in1"]
    q_bar_in = nand1.absanchors["in2"]
    q_in = nand2.absanchors["in1"]
    r_in = nand2.absanchors["in2"]
    q_out = nand1.absanchors["out"]
    q_bar_out = nand2.absanchors["out"]

    _text(drawing, (6.3, s_in[1] + 0.5), "U1a", halign="center", valign="bottom", size=LABEL_SIZE)
    _text(drawing, (6.3, q_in[1] + 0.45), "U1b", halign="center", valign="bottom", size=LABEL_SIZE)
    for anchor, pin in ((s_in, "1"), (q_bar_in, "2"), (q_in, "4"), (r_in, "5")):
        _text(drawing, (anchor[0] + 0.06, anchor[1] + 0.07), pin, halign="left", valign="bottom", size=9.5)
    _text(drawing, (q_out[0] - 0.06, q_out[1] + 0.07), "3", halign="right", valign="bottom", size=9.5)
    _text(drawing, (q_bar_out[0] - 0.06, q_bar_out[1] + 0.07), "6", halign="right", valign="bottom", size=9.5)

    # Switch: the pole is the only terminal tied to GND, and it reaches one
    # contact at a time.  Flipped so the blade leans on the rest contact.
    switch = drawing.add(elm.SwitchSpdt2().at((1.9, 3.4)).up().flip())
    pole = switch.absanchors["a"]
    throw_press = switch.absanchors["c"]
    throw_rest = switch.absanchors["b"]
    drawing.add(elm.Line().at(pole).to((pole[0], 2.9)))
    drawing.add(elm.Ground().at((pole[0], 2.9)))
    _text(drawing, (pole[0] + 0.45, 2.75), "SW1  SPDT", halign="left", valign="center", size=LABEL_SIZE)
    _text(drawing, (0.55, throw_press[1] + 0.22), "pressed", halign="right", valign="bottom")
    _text(drawing, (3.05, throw_rest[1] + 0.22), "rest", halign="left", valign="bottom")

    # S node: the rest contact, its pull-up, and NAND1's upper input.
    s_x = 2.9
    drawing.add(elm.Line().at(throw_rest).to((s_x, throw_rest[1])))
    drawing.add(elm.Line().at((s_x, throw_rest[1])).to((s_x, s_in[1])))
    drawing.add(elm.Dot().at((s_x, s_in[1])))
    drawing.add(elm.Line().at((s_x, s_in[1])).to(s_in))
    drawing.add(elm.Resistor().at((s_x, s_in[1])).to((s_x, 7.4)).label("R1\n10 kΩ", loc="bot"))
    drawing.add(elm.Vdd().at((s_x, 7.4)).label("3V3"))

    # R node: the pressed contact, its pull-up, and NAND2's lower input.
    r_x = 0.9
    drawing.add(elm.Line().at(throw_press).to((r_x, throw_press[1])))
    drawing.add(elm.Dot().at((r_x, throw_press[1])))
    drawing.add(elm.Line().at((r_x, throw_press[1])).to((r_x, r_in[1])))
    drawing.add(elm.Line().at((r_x, r_in[1])).to(r_in))
    drawing.add(elm.Resistor().at((r_x, 5.6)).to((r_x, 7.4)).label("R2\n10 kΩ", loc="top"))
    drawing.add(elm.Line().at((r_x, throw_press[1])).to((r_x, 5.6)))
    drawing.add(elm.Vdd().at((r_x, 7.4)).label("3V3"))

    # Cross-coupling: each output drives the other gate's free input.  The
    # two returns cross once, in open space, with no dot.
    drawing.add(elm.Line().at(q_out).to((8.2, q_out[1])))
    drawing.add(elm.Dot().at((8.2, q_out[1])))
    drawing.add(elm.Line().at((8.2, q_out[1])).to((8.2, 4.3)))
    drawing.add(elm.Line().at((8.2, 4.3)).to((4.9, 4.3)))
    drawing.add(elm.Line().at((4.9, 4.3)).to((4.9, q_in[1])))
    drawing.add(elm.Line().at((4.9, q_in[1])).to(q_in))

    drawing.add(elm.Line().at(q_bar_out).to((8.9, q_bar_out[1])))
    drawing.add(elm.Line().at((8.9, q_bar_out[1])).to((8.9, 3.4)))
    drawing.add(elm.Line().at((8.9, 3.4)).to((5.15, 3.4)))
    drawing.add(elm.Arc2(k=0.35).at((5.15, 3.4)).to((4.65, 3.4)))
    drawing.add(elm.Line().at((4.65, 3.4)).to((4.4, 3.4)))
    drawing.add(elm.Line().at((4.4, 3.4)).to((4.4, q_bar_in[1])))
    drawing.add(elm.Line().at((4.4, q_bar_in[1])).to(q_bar_in))

    # Q on to the pin.
    drawing.add(elm.Line().at((8.2, q_out[1])).to((10.6, q_out[1])))
    _gpio_terminal(drawing, (10.6, q_out[1]))
    _text(drawing, (q_out[0] + 0.15, q_out[1] + 0.15), "Q", halign="left", valign="bottom", size=LABEL_SIZE)
    _text(
        drawing,
        (q_bar_out[0] + 0.15, q_bar_out[1] - 0.15),
        "Q̅",
        halign="left",
        valign="top",
        size=LABEL_SIZE,
    )

    _notes(
        drawing,
        (-0.4, 0.2),
        [
            "The pole reaches one contact at a time, and while it is in the air both",
            "gate inputs sit high, so the latch holds the value it already had. The",
            "bouncing never reaches the pin: settle_ms=0.",
            "At rest the pole grounds the rest contact and Q is HIGH. Pressed, it",
            "grounds the other one and Q goes LOW: Button(pin, active_low=True).",
            "U1 is a 74HC00, two of its four gates, powered from the same 3V3 as the",
            "board. Tie the unused inputs (pins 9, 10, 12, 13) to GND and put 100 nF",
            "across pin 14 and pin 7.",
            "This is the one arrangement that needs a three-terminal switch.",
        ],
    )
    drawing.save(str(path), transparent=True)


FIGURES = {
    "wiring-active-low": wiring_active_low,
    "wiring-active-high": wiring_active_high,
    "debounce-rc": debounce_rc,
    "debounce-rc-schmitt": debounce_rc_schmitt,
    "debounce-spdt-latch": debounce_spdt_latch,
}


def main(argv: list[str] | None = None) -> int:
    """Render every figure, or the one named by ``--figure``."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--figure",
        choices=sorted(FIGURES),
        help="render one figure instead of all five",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=OUT_DIR,
        help=f"destination directory (default: {OUT_DIR.relative_to(REPO_ROOT)})",
    )
    args = parser.parse_args(argv)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    names = [args.figure] if args.figure else sorted(FIGURES)
    for name in names:
        target = args.out_dir / f"{name}.svg"
        FIGURES[name](target)
        print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
